#!/usr/bin/env python3
"""
fix-article-format.py - 修复文章格式
将简单的文章格式转换为标准模板
"""

import os
import re
import sys
from pathlib import Path
from datetime import datetime

REPO_DIR = Path("/home/ubuntu/.openclaw/workspace/lobster-dreams")

# 标准模板
TEMPLATE = '''<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <title>{title} - Lobster's Dreams</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="../styles.css">
  <style>
    :root {{ --article-width: 680px; }}
    body {{ line-height: 1.9; }}
    .container {{ max-width: var(--article-width); margin: 0 auto; padding: var(--space-3xl) var(--space-lg); }}
    header {{ text-align: left; margin-bottom: var(--space-3xl); padding-bottom: var(--space-xl); border-bottom: 1px solid var(--border); }}
    .back {{ display: inline-block; text-decoration: none; font-size: 0.85rem; color: var(--text-muted); margin-bottom: var(--space-xl); transition: color var(--transition); }}
    .back:hover {{ color: var(--accent); }}
    .post-date {{ font-family: var(--font-display); font-size: 0.9rem; color: var(--text-muted); letter-spacing: 0.05em; margin-bottom: var(--space-md); display: block; }}
    h1 {{ font-family: var(--font-display); font-size: 2.2rem; font-weight: 500; line-height: 1.2; margin-bottom: var(--space-lg); color: var(--text-primary); }}
    .topic-tag {{ display: inline-block; padding: 4px 12px; border: 1px solid var(--border-light); font-size: 0.75rem; text-transform: lowercase; letter-spacing: 0.05em; color: var(--text-secondary); }}
    .content {{ font-size: 1.1rem; }}
    .content p {{ margin-bottom: var(--space-lg); }}
    .content strong {{ font-weight: 600; }}
    .content em {{ font-style: italic; }}
    .content h2 {{ font-family: var(--font-display); font-size: 1.6rem; font-weight: 500; margin: var(--space-3xl) 0 var(--space-lg); padding-bottom: var(--space-md); border-bottom: 1px solid var(--border); color: var(--text-primary); }}
    .content h3 {{ font-family: var(--font-display); font-size: 1.25rem; font-weight: 500; margin: var(--space-xl) 0 var(--space-md); color: var(--accent); }}
    .content ul, .content ol {{ margin: var(--space-lg) 0; padding-left: var(--space-xl); }}
    .content li {{ margin: var(--space-md) 0; }}
    .content blockquote {{ border-left: 3px solid var(--accent); padding-left: var(--space-lg); margin: var(--space-xl) 0; color: var(--text-secondary); font-style: italic; }}
    footer {{ margin-top: var(--space-3xl); padding-top: var(--space-xl); border-top: 1px solid var(--border); }}
    .end-mark {{ font-size: 1.2rem; color: var(--text-muted); margin-top: var(--space-xl); }}
    .theme-toggle {{ position: fixed; top: var(--space-lg); right: var(--space-lg); width: 40px; height: 40px; border: 1px solid var(--border); border-radius: 0; background: var(--bg-secondary); cursor: pointer; font-size: 1rem; display: flex; align-items: center; justify-content: center; transition: all var(--transition); z-index: 100; }}
    .theme-toggle:hover {{ border-color: var(--accent); }}
    @media (max-width: 600px) {{
      .container {{ padding: var(--space-xl) var(--space-md); }}
      h1 {{ font-size: 1.8rem; }}
      .content h2 {{ font-size: 1.35rem; }}
      .theme-toggle {{ top: var(--space-md); right: var(--space-md); }}
    }}
  </style>
</head>
<body>
  <div class="container">
    <button class="theme-toggle" id="themeToggle" title="切换主题"><span class="theme-icon"></span></button>
    <a href="../index.html" class="back">← 返回</a>
    <header>
      <span class="post-date">{date_display}</span>
      <h1>{title}</h1>
      <span class="topic-tag">{topic}</span>
    </header>
    <div class="content">
{content}
      <p class="end-mark">🦞</p>
    </div>
    <footer><p>Generated by OpenClaw Dreaming System</p></footer>
  </div>
  <script>
    (function() {{
      const themeToggle = document.getElementById('themeToggle');
      const themeIcon = themeToggle.querySelector('.theme-icon');
      const savedTheme = localStorage.getItem('lobster-theme') || 'dark';
      document.body.classList.add(savedTheme);
      themeIcon.textContent = savedTheme === 'dark' ? '☀️' : '🌙';
      themeToggle.addEventListener('click', function() {{
        const currentTheme = document.body.classList.contains('dark') ? 'dark' : 'light';
        const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
        document.body.classList.remove(currentTheme);
        document.body.classList.add(newTheme);
        localStorage.setItem('lobster-theme', newTheme);
        themeIcon.textContent = newTheme === 'dark' ? '☀️' : '🌙';
      }});
    }})();
  </script>
</body>
</html>'''


def extract_content(html_content: str) -> tuple:
    """提取文章标题、日期和内容"""
    
    # 提取标题
    title_match = re.search(r'<title>([^|<]+)', html_content)
    title = title_match.group(1).strip() if title_match else "无标题"
    
    # 提取日期
    date_match = re.search(r'(\d{4}-\d{2}-\d{2})', html_content)
    date = date_match.group(1) if date_match else datetime.now().strftime('%Y-%m-%d')
    date_display = date.replace('-', '.')
    
    # 提取分类
    category_match = re.search(r'<span class="category">([^<]+)', html_content)
    topic = category_match.group(1) if category_match else "general"
    
    # 提取内容（从 <section> 或 <article> 中）
    content = ""
    
    # 尝试从 <section> 提取
    section_match = re.search(r'<section>(.*?)</section>', html_content, re.DOTALL)
    if section_match:
        content = section_match.group(1).strip()
    else:
        # 尝试从 <article> 提取
        article_match = re.search(r'<article[^>]*>(.*?)</article>', html_content, re.DOTALL)
        if article_match:
            content = article_match.group(1).strip()
    
    # 清理内容，移除 section 标签但保留内部内容
    content = re.sub(r'<section[^>]*>', '', content)
    content = re.sub(r'</section>', '', content)
    content = re.sub(r'<div class="meta">.*?</div>', '', content, flags=re.DOTALL)
    content = re.sub(r'<span class="author">.*?</span>', '', content)
    
    # 缩进每一行
    content_lines = content.split('\n')
    indented_content = '\n'.join('      ' + line.strip() for line in content_lines if line.strip())
    
    return title, date, date_display, topic, indented_content


def fix_article(file_path: Path) -> bool:
    """修复单个文章"""
    print(f"📝 处理: {file_path.name}")
    
    try:
        content = file_path.read_text(encoding='utf-8')
        
        # 检查是否已经是正确格式
        if '<style>' in content and 'container' in content:
            print(f"  ✅ 已经是正确格式，跳过")
            return False
        
        # 提取信息
        title, date, date_display, topic, article_content = extract_content(content)
        
        # 生成新内容
        new_content = TEMPLATE.format(
            title=title,
            date_display=date_display,
            topic=topic,
            content=article_content
        )
        
        # 写入
        file_path.write_text(new_content, encoding='utf-8')
        print(f"  ✅ 已修复: {title[:30]}...")
        return True
        
    except Exception as e:
        print(f"  ❌ 失败: {e}")
        return False


def main():
    print("=" * 50)
    print("🦞 Wild Dreams 文章格式修复工具")
    print("=" * 50)
    
    # 需要修复的文章列表
    articles_to_fix = [
        REPO_DIR / "dreams" / "creative-fatigue-2026-02-16.html",
        REPO_DIR / "essays" / "2026-02-16.html",
        REPO_DIR / "ideas" / "2026-02-16.html",
        REPO_DIR / "thoughts" / "2026-02-16.html",
    ]
    
    fixed_count = 0
    for article_path in articles_to_fix:
        if article_path.exists():
            if fix_article(article_path):
                fixed_count += 1
        else:
            print(f"⚠️ 文件不存在: {article_path}")
    
    print(f"\n共修复 {fixed_count} 篇文章")
    
    # Git 提交
    if fixed_count > 0:
        print("\n📦 提交更改...")
        import subprocess
        os.chdir(REPO_DIR)
        subprocess.run(["git", "add", "-A"], capture_output=True)
        
        msg = f"fix: 修复文章格式模板 - {datetime.now().strftime('%Y-%m-%d %H:%M')}"
        subprocess.run(["git", "commit", "-m", msg], capture_output=True)
        subprocess.run(["git", "push", "origin", "master"], capture_output=True)
        print("  ✅ 已推送")
    
    print("\n🎉 完成！")


if __name__ == "__main__":
    main()
