#!/usr/bin/env python3
"""
validate-article.py - 文章预发布验证
检查文章是否符合标准
"""

import re
import sys
from pathlib import Path
from datetime import datetime

REPO_DIR = Path("/home/ubuntu/.openclaw/workspace/lobster-dreams")
SECTIONS = ["dreams", "thoughts", "ideas", "essays", "reflections", "lifestyle"]

class Validator:
    def __init__(self):
        self.errors = []
        self.warnings = []
        self.passed = 0
    
    def check(self, condition: bool, msg: str, is_error: bool = True):
        if condition:
            self.passed += 1
        else:
            if is_error:
                self.errors.append(msg)
            else:
                self.warnings.append(msg)

def validate_article(file_path: Path) -> dict:
    """验证单个文章"""
    validator = Validator()
    
    try:
        content = file_path.read_text(encoding='utf-8')
        
        # 检查 1: 是否有 style 标签
        has_style = '<style>' in content or '<style ' in content
        validator.check(has_style, f"{file_path.name}: 缺少 <style> 标签", is_error=False)
        
        # 检查 2: 是否有 container
        has_container = 'class="container"' in content
        validator.check(has_container, f"{file_path.name}: 缺少 container", is_error=False)
        
        # 检查 3: 是否有返回链接
        has_back = 'class="back"' in content or 'href="../index.html"' in content
        validator.check(has_back, f"{file_path.name}: 缺少返回链接", is_error=False)
        
        # 检查 4: 是否有 footer
        has_footer = '<footer>' in content or 'Generated by' in content
        validator.check(has_footer, f"{file_path.name}: 缺少 footer", is_error=False)
        
        # 检查 5: 日期格式
        date_match = re.search(r'(\d{4}[-.\}]\d{2}[-.\}]\d{2})', content)
        if date_match:
            validator.check(True, "")
        else:
            validator.errors.append(f"{file_path.name}: 缺少日期")
        
        # 检查 6: 标题
        title_match = re.search(r'<title>([^|<]+)', content)
        if title_match:
            validator.check(True, "")
        else:
            validator.errors.append(f"{file_path.name}: 缺少标题")
        
        # 检查 7: 内容长度
        content_length = len(content)
        if content_length < 1000:
            validator.warnings.append(f"{file_path.name}: 内容过短 ({content_length} chars)")
        
        return {
            "file": file_path.name,
            "valid": len(validator.errors) == 0,
            "errors": validator.errors,
            "warnings": validator.warnings,
            "passed": validator.passed
        }
    
    except Exception as e:
        return {
            "file": file_path.name,
            "valid": False,
            "errors": [f"读取失败: {e}"],
            "warnings": [],
            "passed": 0
        }

def validate_index() -> dict:
    """验证 index.html"""
    validator = Validator()
    index_file = REPO_DIR / "index.html"
    
    if not index_file.exists():
        return {"valid": False, "errors": ["index.html 不存在"]}
    
    content = index_file.read_text(encoding='utf-8')
    
    # 检查文章数量
    post_cards = content.count('class="post-card"')
    validator.check(post_cards > 0, "index 缺少文章卡片")
    
    # 检查统计数字
    total_match = re.search(r'id="totalCount">(\d+)<', content)
    if total_match:
        count = int(total_match.group(1))
        # 允许一定的误差
        if count < post_cards - 2 or count > post_cards + 2:
            validator.warnings.append(f"统计数字 ({count}) 与实际文章数 ({post_cards}) 不符")
    
    return {
        "valid": len(validator.errors) == 0,
        "errors": validator.errors,
        "warnings": validator.warnings
    }

def main():
    print("=" * 60)
    print("🔍 Wild Dreams 文章预发布验证")
    print("=" * 60)
    
    total_errors = 0
    total_warnings = 0
    
    # 验证各板块文章
    print("\n📄 验证文章...")
    for section in SECTIONS:
        section_dir = REPO_DIR / section
        if not section_dir.exists():
            continue
        
        html_files = list(section_dir.glob("*.html"))
        html_files = [f for f in html_files if f.name != "index.html"]
        
        if not html_files:
            continue
        
        print(f"\n  📂 {section}: {len(html_files)} 篇")
        
        for html_file in html_files:
            result = validate_article(html_file)
            
            if result["valid"]:
                print(f"    ✅ {result['file']}")
            else:
                print(f"    ❌ {result['file']}")
                for err in result["errors"]:
                    print(f"       - {err}")
                    total_errors += 1
            
            for warn in result["warnings"]:
                print(f"    ⚠️ {warn}")
                total_warnings += 1
    
    # 验证 index
    print("\n📋 验证 index...")
    index_result = validate_index()
    
    if index_result["valid"]:
        print("    ✅ index.html")
    else:
        print("    ❌ index.html")
        for err in index_result["errors"]:
            print(f"       - {err}")
            total_errors += 1
    
    for warn in index_result["warnings"]:
        print(f"    ⚠️ {warn}")
        total_warnings += 1
    
    # 总结
    print("\n" + "=" * 60)
    if total_errors == 0 and total_warnings == 0:
        print("🎉 全部验证通过！")
    elif total_errors == 0:
        print(f"⚠️ 验证通过，但有 {total_warnings} 个警告")
    else:
        print(f"❌ 验证失败: {total_errors} 个错误, {total_warnings} 个警告")
    print("=" * 60)
    
    # 返回状态码
    sys.exit(0 if total_errors == 0 else 1)

if __name__ == "__main__":
    main()
